export function reportsContracts({spec,endpoint,paginate,object,page,string,id,date,money,methods,paymentStatus}) {
  const optionalId={...id,nullable:true},bool={type:'boolean'};
  const year={type:'integer',minimum:1900,maximum:2200},month={type:'integer',minimum:1,maximum:12};
  const outputMoney={type:'string',pattern:'^-?\\d+\\.\\d{2}$',example:'100.00'},percent={...outputMoney,nullable:true};
  const totals=object({income:outputMoney,expenses:outputMoney,cash_expenses:outputMoney,expected_income:outputMoney,committed_expenses:outputMoney,committed_cash_expenses:outputMoney,fixed_expenses:outputMoney,variable_expenses:outputMoney,installments:outputMoney,payroll_loan:outputMoney,payroll_already_deducted:outputMoney,balance:outputMoney,projected_balance:outputMoney});
  const group=object({key:string,label:string,income:outputMoney,expenses:outputMoney,pending_income:outputMoney,pending_expenses:outputMoney,count:{type:'integer'}});
  const categoryGroup=object({...group.properties,subcategories:{type:'array',items:group}});
  const reportFilters={year,month,date_from:date,date_to:date,category_id:id,subcategory_id:id,account_id:id,card_id:id,merchant_id:id,payment_method:methods,transaction_type:{type:'string',enum:['RECEITA','DESPESA']},status:paymentStatus,is_fixed:bool,group_by:{type:'string',enum:['category','subcategory','account','card','merchant','month','year','fixed']}};
  endpoint('/api/reports/summary','get','Reports','Totais e agrupamento do período filtrado. Cancelados, transferências e pagamentos de fatura são excluídos.',null,object({filters:{type:'object'},totals,groups:{type:'array',items:group},records:{type:'integer'}}));
  spec.paths['/api/reports/summary'].get.parameters.push(...Object.entries(reportFilters).map(([name,schema])=>({name,in:'query',required:false,schema})));
  const dashboard=object({year,month,summary:{...totals,properties:{...totals.properties,planned_amount:outputMoney,actual_amount:outputMoney,budget_usage_percent:percent}},
    by_category:{type:'array',items:categoryGroup},by_account:{type:'array',items:group},by_card:{type:'array',items:group},highlights:{type:'array',items:object({label:string,amount:outputMoney})},
    monthly_evolution:{type:'array',items:object({month:{type:'integer'},label:string,...totals.properties})},annual_evolution:{type:'array',items:object({year:{type:'integer'},...totals.properties})},
    budget:{type:'object'},fortnight:{type:'object'},accounts:{type:'array',items:object({id,name:string,current_balance:outputMoney})},future_installments:{type:'array',items:group},upcoming:{type:'array',items:{type:'object'}},warnings:{type:'array',items:string}});
  endpoint('/api/dashboard','get','Reports','Painel do mês: totais, evolução mensal/anual, orçamento, quinzena, contas e próximos vencimentos.',null,dashboard);
  spec.paths['/api/dashboard'].get.parameters.push({name:'year',in:'query',required:false,schema:year},{name:'month',in:'query',required:false,schema:month});
  const reportTransaction=object({id,description:string,transaction_type:{type:'string',enum:['RECEITA','DESPESA']},amount:outputMoney,transaction_date:date,status:paymentStatus,category:{type:'object',nullable:true},subcategory:{type:'object',nullable:true},account:{type:'object',nullable:true},card:{type:'object',nullable:true},merchant:{type:'object',nullable:true}});
  endpoint('/api/reports/transactions','get','Reports','Listar lançamentos do período filtrado, com relações carregadas, ordenados por data.',null,page(reportTransaction));
  paginate('/api/reports/transactions',reportFilters);
  spec.paths['/api/reports/export']={get:{tags:['Reports'],operationId:'get_api_reports_export',summary:'Exportar lançamentos filtrados em CSV.',description:'CSV com BOM UTF-8, separado por ponto e vírgula; texto que pareça fórmula é escapado. Mesmos filtros de reports/summary.',
    security:[{bearerAuth:[]}],parameters:Object.entries(reportFilters).map(([name,schema])=>({name,in:'query',required:false,schema})),
    responses:{200:{description:'Arquivo CSV.',content:{'text/csv':{schema:{type:'string',format:'binary'}}}},401:{$ref:'#/components/responses/ApiError'},422:{$ref:'#/components/responses/ApiError'}}}};
  const importRecord=object({id,original_filename:string,format:{type:'string',enum:['CSV','OFX']},account_id:optionalId,card_id:optionalId,column_mapping:{type:'object',nullable:true},status:{type:'string',enum:['PREVIA','PROCESSANDO','CONCLUIDA','FALHOU']},confirmed_at:{type:'string',format:'date-time',nullable:true},
    columns:{type:'array',items:string},counts:object({total:{type:'integer'},selected:{type:'integer'},imported:{type:'integer'},duplicates:{type:'integer'},invalid:{type:'integer'},left_out:{type:'integer',description:'Linhas válidas ainda não selecionadas nem importadas.'}})});
  endpoint('/api/imports','get','Imports','Listar importações do usuário.',null,page(importRecord));paginate('/api/imports');
  spec.paths['/api/imports'].post={tags:['Imports'],operationId:'post_api_imports',summary:'Enviar arquivo CSV ou OFX (até 2 MB) para uma conta ou cartão, exclusivamente. Gera prévia com mapeamento sugerido, sem gravar lançamentos.',
    security:[{bearerAuth:[]}],parameters:[],requestBody:{required:true,content:{'multipart/form-data':{schema:object({file:{type:'string',format:'binary'},account_id:optionalId,card_id:optionalId})}}},
    responses:{201:{description:'Arquivo recebido.',content:{'application/json':{schema:object({success:{type:'boolean',enum:[true]},message:string,data:importRecord,errors:{type:'array',items:string}})}}},401:{$ref:'#/components/responses/ApiError'},422:{$ref:'#/components/responses/ApiError'}}};
  endpoint('/api/imports/{id}','get','Imports','Consultar importação e contagens por situação.',null,importRecord);
  const importRow=object({id,import_id:id,row_number:{type:'integer'},raw_data:{type:'object',nullable:true},mapped_data:{type:'object',nullable:true},fingerprint:{type:'string',nullable:true},status:{type:'string',enum:['PENDENTE','IMPORTADA','DUPLICADA','INVALIDA']},validation_errors:{type:'object',nullable:true},selected:bool});
  endpoint('/api/imports/{id}/rows','get','Imports','Listar linhas da importação, já mapeadas para revisão.',null,page(importRow));paginate('/api/imports/{id}/rows');
  const mapping=object({date:string,description:string,amount:string,type:{...string,nullable:true},date_format:{type:'string',enum:['Y-m-d','d/m/Y','m/d/Y','OFX']},number_format:{type:'string',enum:['pt-BR','en-US']},transaction_type:{type:'string',enum:['RECEITA','DESPESA'],nullable:true},expense_category_id:optionalId,income_category_id:optionalId,payment_method:{...methods,nullable:true}},['date','description','amount','date_format','number_format']);
  endpoint('/api/imports/{id}/mapping','put','Imports','Aplicar mapeamento de colunas e recalcular prévia: normaliza, detecta duplicidade por conta/cartão e desmarca possíveis transferências/faturas.',mapping,importRecord,{example:{date:'Data',description:'Descrição',amount:'Valor',date_format:'d/m/Y',number_format:'pt-BR'}});
  const rowEdit=object({category_id:optionalId,subcategory_id:optionalId,description:string,transaction_type:{type:'string',enum:['RECEITA','DESPESA']},selected:bool});
  endpoint('/api/import-rows/{id}','put','Imports','Corrigir categoria, descrição, tipo ou seleção de uma linha antes ou depois de uma confirmação parcial. Linhas já importadas não podem mais ser alteradas por aqui.',rowEdit,importRow,{example:{category_id:1,selected:true}});
  const bulkRowEdit=object({updates:{type:'array',minItems:1,maxItems:200,items:object({id,...rowEdit.properties},['id'])}},['updates']);
  endpoint('/api/imports/{id}/rows','put','Imports','Atualizar várias linhas de uma vez (categoria, descrição, tipo e seleção), sem exigir uma requisição por linha. Cartão só aceita despesa; linhas já importadas retornam em failed.',bulkRowEdit,object({updated:{type:'integer'},failed:{type:'array',items:object({id,message:string})},import:importRecord}),{example:{updates:[{id:1,category_id:1,selected:true},{id:2,selected:false}]}});
  endpoint('/api/imports/{id}/confirm','post','Imports','Gravar lançamentos das linhas selecionadas, ainda não importadas e válidas. Pode ser chamada de novo após uma importação concluída para gravar linhas selecionadas posteriormente, sem duplicar as já importadas. Linhas já duplicadas na confirmação são marcadas sem interromper as demais.',null,importRecord,{example:{}});
}
