<?php
return [
    'dashboard'=>['title'=>'Visão geral','group'=>'Seu financeiro','icon'=>'dashboard'],
    'transactions'=>['title'=>'Lançamentos','group'=>'Financeiro','icon'=>'list','resource'=>'transactions'],
    'incomes'=>['title'=>'Receitas','group'=>'Financeiro','icon'=>'up','resource'=>'transactions','filters'=>['transaction_type'=>'RECEITA']],
    'expenses'=>['title'=>'Despesas','group'=>'Financeiro','icon'=>'down','resource'=>'transactions','filters'=>['transaction_type'=>'DESPESA']],
    'transfers'=>['title'=>'Transferências','group'=>'Financeiro','icon'=>'transfer','resource'=>'transfers'],
    'accounts'=>['title'=>'Contas bancárias','group'=>'Contas e cartões','icon'=>'wallet','resource'=>'accounts'],
    'cards'=>['title'=>'Cartões','group'=>'Contas e cartões','icon'=>'card','resource'=>'cards'],
    'card-invoices'=>['title'=>'Faturas','group'=>'Contas e cartões','icon'=>'receipt','resource'=>'card-invoices'],
    'budgets'=>['title'=>'Orçamento mensal','group'=>'Planejamento','icon'=>'budget'],
    'fortnight'=>['title'=>'Por quinzena','group'=>'Planejamento','icon'=>'calendar'],
    'fixed-expenses'=>['title'=>'Contas fixas','group'=>'Planejamento','icon'=>'repeat','resource'=>'fixed-expenses'],
    'subscriptions'=>['title'=>'Assinaturas','group'=>'Planejamento','icon'=>'layers','resource'=>'subscriptions'],
    'income-schedules'=>['title'=>'Receitas recorrentes','group'=>'Planejamento','icon'=>'up','resource'=>'income-schedules'],
    'goals'=>['title'=>'Metas','group'=>'Planejamento','icon'=>'target','resource'=>'goals'],
    'loans'=>['title'=>'Empréstimos e consignado','group'=>'Dívidas','icon'=>'bank','resource'=>'loans'],
    'installments'=>['title'=>'Parcelamentos','group'=>'Dívidas','icon'=>'layers','resource'=>'installments'],
    'reports'=>['title'=>'Relatórios','group'=>'Análise','icon'=>'chart'],
    'imports'=>['title'=>'Importar extrato','group'=>'Análise','icon'=>'upload'],
    'settings'=>['title'=>'Configurações','group'=>'Organização','icon'=>'settings'],
    'categories'=>['title'=>'Categorias','group'=>'Organização','icon'=>'tag'],
    'merchants'=>['title'=>'Estabelecimentos','group'=>'Organização','icon'=>'store','resource'=>'merchants'],
];
